# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wk8CDw_0Kx8OyYFP63_xL9ps1RYYGrFc
"""

import pandas as pd
import nltk
from nlpaug.augmenter.word import RandomWordAug
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

nltk.download('punkt')